const productos = [
  {
    id: 1,
    imagen: "https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f",
    descripcion: "Corte tradicional para caballero con acabado limpio.",
    nombre: "Shampoo Hidratante",
    costo: 15,
    precio: 35,
    get ganancia() { return this.precio - this.costo; },
    stock: 20,
    categoria_id: 1,
    estado: true,
    fecha_registro: "2026-01-12"
  },
  {
    id: 2,
    imagen: "https://images.unsplash.com/photo-1515377905703-c4788e51af15",
    descripcion: "Corte tradicional para caballero con acabado limpio.",
    nombre: "Acondicionador Reparador",
    costo: 18,
    precio: 42,
    get ganancia() { return this.precio - this.costo; },
    stock: 15,
    categoria_id: 1,
    estado: true,
    fecha_registro: "2026-01-18"
  },
  {
    id: 3,
    imagen: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9",
    descripcion: "Corte tradicional para caballero con acabado limpio.",
    nombre: "Mascarilla Capilar",
    costo: 22,
    precio: 55,
    get ganancia() { return this.precio - this.costo; },
    stock: 10,
    categoria_id: 2,
    estado: true,
    fecha_registro: "2026-02-05"
  },
  {
    id: 4,
    imagen: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f",
    descripcion: "Corte tradicional para caballero con acabado limpio.",
    nombre: "Tinte Rojo Intenso",
    costo: 35,
    precio: 80,
    get ganancia() { return this.precio - this.costo; },
    stock: 8,
    categoria_id: 3,
    estado: true,
    fecha_registro: "2026-02-20"
  },
  {
    id: 5,
    imagen: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c",
    descripcion: "Corte tradicional para caballero con acabado limpio.",
    nombre: "Secadora Profesional",
    costo: 140,
    precio: 250,
    get ganancia() { return this.precio - this.costo; },
    stock: 5,
    categoria_id: 4,
    estado: true,
    fecha_registro: "2026-03-01"
  },
  {
    id: 6,
    imagen: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796",
    descripcion: "Corte tradicional para caballero con acabado limpio.",
    nombre: "Plancha de Cabello",
    costo: 95,
    precio: 180,
    get ganancia() { return this.precio - this.costo; },
    stock: 7,
    categoria_id: 4,
    estado: true,
    fecha_registro: "2026-03-15"
  },
  {
    id: 7,
    imagen: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1",
    descripcion: "Corte tradicional para caballero con acabado limpio.",
    nombre: "Aceite de Argán",
    costo: 28,
    precio: 65,
    get ganancia() { return this.precio - this.costo; },
    stock: 18,
    categoria_id: 2,
    estado: true,
    fecha_registro: "2026-04-08"
  },
  {
    id: 8,
    imagen: "https://images.unsplash.com/photo-1496747611176-843222e1e57c",
    descripcion: "Corte tradicional para caballero con acabado limpio.",
    nombre: "Cepillo Redondo",
    costo: 10,
    precio: 25,
    get ganancia() { return this.precio - this.costo; },
    stock: 30,
    categoria_id: 4,
    estado: true,
    fecha_registro: "2026-04-21"
  },
  {
    id: 9,
    imagen: "https://images.unsplash.com/photo-1517841905240-472988babdf9",
    descripcion: "Corte tradicional para caballero con acabado limpio.",
    nombre: "Spray Fijador",
    costo: 12,
    precio: 28,
    get ganancia() { return this.precio - this.costo; },
    stock: 12,
    categoria_id: 1,
    estado: false,
    fecha_registro: "2026-05-10"
  },
  {
    id: 10,
    imagen: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f",
    descripcion: "Corte tradicional para caballero con acabado limpio.",
    nombre: "Kit de Barbería",
    costo: 180,
    precio: 320,
    get ganancia() { return this.precio - this.costo; },
    stock: 4,
    categoria_id: 4,
    estado: true,
    fecha_registro: "2026-05-25"
  }
];

export default productos;