const servicios = [
  {
    id: 1,
    nombre: "Corte Clásico",
    descripcion: "Corte tradicional para caballero con acabado limpio.",
    precio: 25,
    duracion: 10,
    estado: true,
    fecha_registro: "2026-01-10",
    categoria_id: 1,
    imagen: ""
  },
  {
    id: 2,
    nombre: "Balayage Rubio",
    descripcion: "Técnica de coloración degradada en tonos rubios.",
    precio: 180,
    duracion: 20,
    estado: true,
    fecha_registro: "2025-11-22",
    categoria_id: 4,
    imagen: "https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f"
  },
  {
    id: 3,
    nombre: "Alisado Brasileño",
    descripcion: "Tratamiento capilar para reducir el frizz y alisar.",
    precio: 220,
    duracion: 30,
    estado: true,
    fecha_registro: "2025-09-15",
    categoria_id: 2,
    imagen: ""
  },
  {
    id: 4,
    nombre: "Peinado para Fiesta",
    descripcion: "Peinado elegante para eventos especiales.",
    precio: 90,
    duracion: 40,
    estado: true,
    fecha_registro: "2026-02-05",
    categoria_id: 3,
    imagen: "https://images.unsplash.com/photo-1517841905240-472988babdf9"
  },
  {
    id: 5,
    nombre: "Tinte Negro Azulado",
    descripcion: "Aplicación completa de tinte negro con reflejos azulados.",
    precio: 140,
    duracion: 60,
    estado: false,
    fecha_registro: "2025-08-30",
    categoria_id: 4,
    imagen: ""
  },
  {
    id: 6,
    nombre: "Corte Degradado",
    descripcion: "Corte moderno con degradado lateral.",
    precio: 35,
    duracion: 90,
    estado: true,
    fecha_registro: "2026-03-11",
    categoria_id: 1,
    imagen: ""
  },
  {
    id: 7,
    nombre: "Hidratación Capilar",
    descripcion: "Tratamiento nutritivo para cabello seco o dañado.",
    precio: 75,
    duracion: 120,
    estado: true,
    fecha_registro: "2025-12-01",
    categoria_id: 2,
    imagen: ""
  },
  {
    id: 8,
    nombre: "Ondas Sueltas",
    descripcion: "Peinado con ondas naturales y volumen.",
    precio: 60,
    duracion: 150,
    estado: true,
    fecha_registro: "2026-01-28",
    categoria_id: 3,
    imagen: ""
  },
  {
    id: 9,
    nombre: "Mechas Plateadas",
    descripcion: "Aplicación de mechas color plata modernas.",
    precio: 200,
    duracion: 180,
    estado: false,
    fecha_registro: "2025-07-19",
    categoria_id: 4,
    imagen: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f"
  },
  {
    id: 10,
    nombre: "Botox Capilar",
    descripcion: "Tratamiento reparador para brillo y suavidad.",
    precio: 160,
    duracion: 10,
    estado: true,
    fecha_registro: "2025-10-12",
    categoria_id: 2,
    imagen: ""
  },
  {
    id: 11,
    nombre: "anaranjados",
    descripcion: "diseño anatranjados",
    precio: 120,
    duracion: 20,
    estado: true,
    fecha_registro: "2020-10-10",
    categoria_id: 4,
    imagen: ""
  },
  {
    id: 12,
    nombre: "dorado color",
    descripcion: "diseño dorados",
    precio: 180,
    duracion: 30,
    estado: false,
    fecha_registro: "2025-10-12",
    categoria_id: 4,
    imagen: ""
  },
  {
    id: 13,
    nombre: "diseño morado",
    descripcion: "cabello morado",
    precio: 16,
    duracion: 40,
    estado: false,
    fecha_registro: "2025-12-12",
    categoria_id: 3,
    imagen: ""
  },
  {
    id: 14,
    nombre: "diseño rojo",
    descripcion: "cabello rojizo",
    precio: 100,
    duracion: 60,
    estado: true,
    fecha_registro: "2026-01-12",
    categoria_id: 3,
    imagen: ""
  },
  {
    id: 15,
    nombre: "Corte Bob",
    descripcion: "Corte de cabello estilo bob moderno a la altura de la mandíbula.",
    precio: 90,
    duracion: 90,
    estado: true,
    fecha_registro: "2026-02-15",
    categoria_id: 1,
    imagen: ""
  },
  {
    id: 16,
    nombre: "Corte de Puntas",
    descripcion: "Mantenimiento básico para eliminar puntas abiertas.",
    precio: 20,
    duracion: 120,
    estado: true,
    fecha_registro: "2026-03-01",
    categoria_id: 1,
    imagen: ""
  },
  {
    id: 17,
    nombre: "Corte Pixie",
    descripcion: "Corte muy corto y atrevido, ideal para definir facciones.",
    precio: 50,
    duracion: 150,
    estado: true,
    fecha_registro: "2026-01-20",
    categoria_id: 1,
    imagen: ""
  },
  {
    id: 18,
    nombre: "Corte para Niños",
    descripcion: "Corte dinámico y rápido adaptado para los más pequeños.",
    precio: 15,
    duracion: 180,
    estado: true,
    fecha_registro: "2026-02-10",
    categoria_id: 1,
    imagen: ""
  },
  {
    id: 19,
    nombre: "Corte en Capas",
    descripcion: "Corte largo que aporta volumen y movimiento al cabello.",
    precio: 40,
    duracion: 10,
    estado: true,
    fecha_registro: "2026-03-05",
    categoria_id: 1,
    imagen: ""
  },
  {
    id: 20,
    nombre: "Perfilado de Barba",
    descripcion: "Corte y diseño de barba con navaja y toalla caliente.",
    precio: 22,
    duracion: 20,
    estado: true,
    fecha_registro: "2026-01-15",
    categoria_id: 1,
    imagen: ""
  },
  {
    id: 21,
    nombre: "Cauterización Capilar",
    descripcion: "Tratamiento térmico para sellar la cutícula del cabello dañado.",
    precio: 130,
    duracion: 30,
    estado: true,
    fecha_registro: "2025-11-05",
    categoria_id: 2,
    imagen: ""
  },
  {
    id: 22,
    nombre: "Exfoliación Desintoxicante",
    descripcion: "Tratamiento profundo para purificar el cuero cabelludo.",
    precio: 55,
    duracion: 40,
    estado: true,
    fecha_registro: "2025-12-18",
    categoria_id: 2,
    imagen: ""
  },
  {
    id: 23,
    nombre: "Mascarilla de Queratina",
    descripcion: "Nutrición intensa para reponer la masa capilar perdida.",
    precio: 85,
    duracion: 60,
    estado: true,
    fecha_registro: "2026-02-14",
    categoria_id: 2,
    imagen: ""
  },
  {
    id: 24,
    nombre: "Tratamiento Anti-caída",
    descripcion: "Ampolletas y masajes capilares para fortalecer la raíz.",
    precio: 95,
    duracion: 90,
    estado: true,
    fecha_registro: "2026-03-20",
    categoria_id: 2,
    imagen: ""
  },
  {
    id: 25,
    nombre: "Brillo de Seda",
    descripcion: "Baño de nutrientes que otorga un reflejo espejo instantáneo.",
    precio: 110,
    duracion: 120,
    estado: true,
    fecha_registro: "2026-01-08",
    categoria_id: 2,
    imagen: ""
  },
  {
    id: 26,
    nombre: "Recogido Alto Elegante",
    descripcion: "Moño alto pulido ideal para novias y graduaciones.",
    precio: 120,
    duracion: 150,
    estado: true,
    fecha_registro: "2026-02-28",
    categoria_id: 3,
    imagen: ""
  },
  {
    id: 27,
    nombre: "Trenzas Africanas Medias",
    descripcion: "Peinado con trenzas pegadas de larga duración.",
    precio: 150,
    duracion: 180,
    estado: true,
    fecha_registro: "2025-09-02",
    categoria_id: 3,
    imagen: ""
  },
  {
    id: 28,
    nombre: "Semi-recogido con Ondas",
    descripcion: "Peinado romántico que combina sujeción superior y ondas.",
    precio: 80,
    duracion: 10,
    estado: true,
    fecha_registro: "2026-03-15",
    categoria_id: 3,
    imagen: ""
  },
  {
    id: 29,
    nombre: "Brushing Extra Liso",
    descripcion: "Secado con cepillo redondo que aporta un alisado natural.",
    precio: 40,
    duracion: 20,
    estado: true,
    fecha_registro: "2026-02-11",
    categoria_id: 3,
    imagen: ""
  },
  {
    id: 30,
    nombre: "Peinado Boho Chic",
    descripcion: "Estilo desenfadado con sutiles trenzas y texturizado suelto.",
    precio: 70,
    duracion: 30,
    estado: true,
    fecha_registro: "2025-11-30",
    categoria_id: 3,
    imagen: ""
  },
  {
    id: 31,
    nombre: "Tinte Raíces",
    descripcion: "Retoque de color para cubrir el crecimiento capilar y canas.",
    precio: 65,
    duracion: 40,
    estado: true,
    fecha_registro: "2026-03-02",
    categoria_id: 4,
    imagen: ""
  },
  {
    id: 32,
    nombre: "Mechas Californianas",
    descripcion: "Degradado marcado simulando el aclarado natural del sol.",
    precio: 160,
    duracion: 60,
    estado: true,
    fecha_registro: "2025-10-25",
    categoria_id: 4,
    imagen: ""
  },
  {
    id: 33,
    nombre: "Reflejos Dorados",
    descripcion: "Luces finas para iluminar cabellos castaños.",
    precio: 130,
    duracion: 120,
    estado: true,
    fecha_registro: "2026-01-22",
    categoria_id: 4,
    imagen: ""
  },
  {
    id: 34,
    nombre: "Tinte Fantasía Rosa",
    descripcion: "Decoloración previa y aplicación de tono rosa pastel.",
    precio: 190,
    duracion: 90,
    estado: true,
    fecha_registro: "2025-08-14",
    categoria_id: 4,
    imagen: ""
  },
  {
    id: 35,
    nombre: "Baño de Color Cobrizo",
    descripcion: "Intensificación del brillo en tonos rojizos sin amoníaco.",
    precio: 75,
    duracion: 60,
    estado: true,
    fecha_registro: "2026-02-20",
    categoria_id: 4,
    imagen: ""
  },
  {
    id: 36,
    nombre: "Coke Shag",
    descripcion: "Corte setentero con muchas capas y flequillo texturizado.",
    precio: 48,
    duracion: 150,
    estado: true,
    fecha_registro: "2026-04-01",
    categoria_id: 1,
    imagen: ""
  },
  {
    id: 37,
    nombre: "Rapado con Diseño (Hair Tattoo)",
    descripcion: "Líneas y figuras artísticas creadas con trimmer en el rapado.",
    precio: 30,
    duracion: 180,
    estado: true,
    fecha_registro: "2026-04-10",
    categoria_id: 1,
    imagen: ""
  },
  {
    id: 38,
    nombre: "Tratamiento de Ácido Hialurónico",
    descripcion: "Relleno capilar para cabellos finos, opacos y quebradizos.",
    precio: 175,
    duracion: 10,
    estado: true,
    fecha_registro: "2026-03-18",
    categoria_id: 2,
    imagen: ""
  },
  {
    id: 39,
    nombre: "Shock de Aminoácidos",
    descripcion: "Reconstrucción SOS para cabellos elásticos post-decoloración.",
    precio: 145,
    duracion: 90,
    estado: true,
    fecha_registro: "2026-02-25",
    categoria_id: 2,
    imagen: ""
  },
  {
    id: 40,
    nombre: "Peinado de Novia Express",
    descripcion: "Prueba rápida de peinado alto sin accesorios complejos.",
    precio: 85,
    duracion: 60,
    estado: false,
    fecha_registro: "2025-06-12",
    categoria_id: 3,
    imagen: ""
  },
  {
    id: 41,
    nombre: "Coleta Pulida Texturizada",
    descripcion: "Ponytail alta ideal para sesiones fotográficas o salidas.",
    precio: 55,
    duracion: 40,
    estado: true,
    fecha_registro: "2026-04-12",
    categoria_id: 3,
    imagen: ""
  },
  {
    id: 42,
    nombre: "Balayage Invertido",
    descripcion: "Técnica para devolver profundidad oscura a cabellos muy rubios.",
    precio: 165,
    duracion: 120,
    estado: true,
    fecha_registro: "2026-01-30",
    categoria_id: 4,
    imagen: ""
  },
  {
    id: 43,
    nombre: "Platinado Global",
    descripcion: "Decoloración total desde la raíz para alcanzar un rubio nórdico.",
    precio: 250,
    duracion: 180,
    estado: false,
    fecha_registro: "2025-09-19",
    categoria_id: 4,
    imagen: ""
  },
  {
    id: 44,
    nombre: "Tinte Chocolate Clásico",
    descripcion: "Cobertura uniforme en un tono marrón cálido y brillante.",
    precio: 90,
    duracion: 90,
    estado: true,
    fecha_registro: "2026-04-15",
    categoria_id: 4,
    imagen: ""
  }
];

export default servicios;